### ISSUE TITLE
Support thrift maps

### ISSUE THREAD

**Issue by tomrf1** [guardian/fezziwig#3] opened 2017-01-17 21:34 UTC
The `map` type is not currently supported. In [content-api-models](https://github.com/guardian/content-api-models) we have custom encoders/decoders to work around this.

Ordinarily circe is able to provide encoders/decoders for scala maps. But I haven't been able to get this library's macros to infer implicits.

The macros use shapeless' `Lazy` to find implicit encoders/decoders for nested types where the compiler has given up due to implicit divergence. But for maps even this fails, presumably because it has two type parameters. There must be some shapeless magic we can do to fix this.

**Comment by mchv** [comment] 2017-01-18 17:39
@cb372 I am sure you **can't** take up this challenge!

**Comment by cb372** [comment] 2017-01-20 18:14
Thank you, your bait was delicious.

The problem is that circe only provides a decoder for subclasses of `scala.collection.immutable.Map` (see the [sig](https://github.com/circe/circe/blob/6101fb6f27ba6b3be57df95584a7beba31c89c41/modules/core/shared/src/main/scala/io/circe/Decoder.scala#L649) `decodeMapLike` and the [import](https://github.com/circe/circe/blob/6101fb6f27ba6b3be57df95584a7beba31c89c41/modules/core/shared/src/main/scala/io/circe/Decoder.scala#L10) at the top of the file). Scrooge, on the other hand, uses `scala.collection.Map` in its generated code. Not sure why.

You could try lobbying @travisbrown to add an encoder/decoder for `scala.collection.Map` to circe, but I'm not sure how keen he would be. Or you could write your own pretty easily.

**Comment by travisbrown** [comment] 2017-01-20 18:58
No public methods in circe mutate anything, but I don't feel any particular need to be fundamentalist about providing instances for mutable data types. We already have instances for mutable sequences, so supporting `scala.collection.Map` would probably be more consistent. If you want to open an issue there's a good chance we'd add it.

**Comment by mchv** [comment] 2017-01-21 18:21
@cb372 your kindness can only be matched by your scala skills level. Thanks for looking into this!
@travisbrown thank you for taking time to comment, this is actually a great opportunity for me to contribute to circe 😃

**Comment by emdash-ie** [comment] 2024-10-10 16:05
I believe we can close this issue, as [this comment in the linked circe issue](https://github.com/circe/circe/issues/555#issuecomment-310943582) says that support was merged in 2017.

**Closed as completed by emdash-ie** 2024-10-10 16:05 UTC
